version: '3.9'

services:
  web:
    build: .
    command: python3 /code/manage.py runserver 0.0.0.0:8000
    # for production:
    # command: gunicorn django_project.wsgi -b 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    environment:
      - "DJANGO_SECRET_KEY=django-insecure-hv1(e0r@v4n4m6gqdz%dn(60o=dsy8&@0_lbs8p-v3u^bs4)xl"
      - "DJANGO_DEBUG=True"
      - "DJANGO_SECURE_SSL_REDIRECT=False"
      - "DJANGO_SECURE_HSTS_SECONDS=0"
      - "DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS=False"
      - "DJANGO_SECURE_HSTS_PRELOAD=False"
      - "DJANGO_SESSION_COOKIE_SECURE=False"
      - "DJANGO_CSRF_COOKIE_SECURE=False"
    depends_on:
      - db
    links:
      - db:db
    networks:
      default:

  db:
    restart: always
    container_name: bookstore_pg
    image: postgres:11
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    volumes:
      - postgres_data:/var/lib/postgresql/postgresdata
    ports:
      - 5433:5433
    networks:
      default:

  redis:
    image: redis:latest
    container_name: bookstore_redis
    volumes:
      - cache:/data
    ports:
      - 6379:6379


volumes:
  postgres_data:
  cache:
networks:
  default:
